### ISSUE TITLE
Update multiple file of application

### ISSUE THREAD

**Issue by bs135** [henryxrl/SharpUpdate#1]
My prolem: my application include 2 files **app.exe** and **library.dll**, so how to use SharpUpdate to update both of them?

**Comment by Jhonnybmx** [comment]
I would also like this option

**Comment by sevenbitsAnmol** [comment]
yes this Class library needs this functionality very much...!

**Comment by sevenbitsAnmol** [comment]
Does anyone try to make this Class library handling multiple file updation ?

**Comment by jr0driguezv** [comment]
@henryxrl Thank you very much for the library works perfect, but I join this, I also need to be able to download multiple files Please!

**Comment by henryxrl** [comment]
Sorry guys, didn't have time to work on this till now. Support for updating multiple files is coming.

**Comment by jr0driguezv** [comment]
@henryxrl Okay, waiting for that, although I could really have many improvements such as driving back to the previous version if a problem occurs, the user can degrade to the previous version and thanks for responding.

**Comment by henryxrl** [comment]
Requested features have now been implemented.
